name: Run unit tests

on:
  pull_request:

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Bun
        run: npm i -g bun

      - name: Install dependencies
        run: bun i

      - name: Run linter with auto-fix
        run: bun test
